spring:
  config:
    import: optional:classpath:/application.yml

  application:
    name: api-gateway

  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: course-service
          uri: http://localhost:8081
          predicates:
            - Path=/courses/**
        - id: enrollement-service
          uri: http://localhost:8083
          predicates:
            - Path=/enrollments/**
        - id: student-service
          uri: http://localhost:8082
          predicates:
            - Path=/students/**
    loadbalancer:
      rule: random

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
